"""Record implementation feasibility for every currently missing or failed case."""
import json,hashlib
from pathlib import Path
coverage=json.loads(Path('COVERAGE.json').read_text()); cases=[]
def add(stack,scenario,disposition,label,reason,action,evidence,metric=None):
 cases.append(dict(stack=stack,scenario=scenario,metric=metric,disposition=disposition,label=label,reason=reason,nextStep=action,evidence=evidence))
add('electric','deep-relationship-query','implement','Not implemented','The adapter returns a placeholder; Electric supplies the shape data needed to compute both screens.','Load task, project and organization shapes, build indexed lookup maps, and validate identical joined rows and dashboard totals.',['src/adapters/electric.ts','src/contracts/screens.ts'])
add('jazz-v2','deep-relationship-query','implement','Not implemented','The installed SDK exports native relationship include queries; our fixture only defines tasks and memberships.','Add project/organization tables and references with indexes, independently seed them, use native includes for detail and declared application aggregation for dashboard.',['src/adapters/jazz-native.ts','node_modules/jazz-tools/dist/typed-app.d.ts'])
add('electric','replica-reopen','implement','Not implemented','An application-owned SQLite cache already exists in the recovery driver; the adapter has no reopen entrypoint.','Reuse that cache with lazy transport, wire runReplicaReopen, and verify both routes blocked and the same durable file reopened. Label application-owned persistence.',['src/recovery/electric-driver.ts','src/recovery/reopen.ts'])
add('zero','replica-reopen','implement','Not implemented','The selected native-host configuration uses memory; the existing browser client already selects native IndexedDB.','Use a persistent Chromium profile and stable storage identity; close and relaunch fully offline and validate all 2000 records. Keep browser samples separate.',['src/browser/client-entry.ts','node_modules/@rocicorp/zero/out/zero-client/src/client/options.d.ts'])
add('electric-tanstack','offline-restart','implement','Not implemented','fake-indexeddb makes the current queue volatile; the installed executor accepts a StorageAdapter.','Supply a durable SQLite storage adapter or real browser IndexedDB; preserve collection/outbox identities, use native executor restoration, kill before replay and validate every edit.',['src/recovery/tanstack-driver.ts','node_modules/@tanstack/offline-transactions/src/types.ts'])
add('zero','offline-restart','diagnose','Needs persistent test','Memory storage explains the current skip, but IndexedDB alone does not prove immediate crash durability. Zero limits offline writes by connection state.','Probe the canonical short-outage workload with native IndexedDB and forced process death; inspect native queue survival and client receipts without app-level replay or an extended disconnect timeout.',['src/recovery/zero-driver.ts','src/browser/client-entry.ts','https://zero.rocicorp.dev/docs/connection'])
add('powersync','blob-flow','implement','Not implemented','The installed Node SDK includes an attachment queue and filesystem storage; a local 2 MiB staging/reopen probe passes.','Wire AttachmentQueue to the shared object store and metadata references, then validate upload, fresh download and interrupted-download recovery. Declare the helper experimental.',['node_modules/@powersync/common/lib/attachments/AttachmentQueue.d.ts','node_modules/@powersync/node/lib/attachments/NodeFileSystemAdapter.d.ts','results/diagnostics/final-publication/CAPABILITY-PROBE.json','https://docs.powersync.com/client-sdks/advanced/attachments'])
add('jazz-v2','blob-flow','implement','Not implemented','Jazz 2 alpha has chunked file creation/loading APIs; our adapter returns a placeholder.','Add files/file_parts schema and native file operations; verify exact bytes and recovery with fresh native stores. Express milestones by observable bytes and native durability rather than S3-specific requests.',['node_modules/jazz-tools/dist/runtime/db.d.ts','node_modules/jazz-tools/dist/runtime/file-storage.d.ts','results/diagnostics/final-publication/CAPABILITY-PROBE.json'])
for stack in ['electric','electric-tanstack','zero','turso']:
 add(stack,'blob-flow','implement-application-path','Not implemented','No standalone attachment queue is wired for this adapter; the application can sync file references and use object storage.','Implement one shared application-owned object-transfer queue, with each product syncing metadata. Separate product-owned versus application-owned transfer machinery; do not imply native attachment support.',['src/adapters/'+stack+'.ts','src/contracts/attachments.ts','src/attachments/run.ts'])
add('turso','permission-change','not-equivalent','No equivalent','The pinned local sync server exposes database replication, not per-actor row revocation while retaining other actors and server data. Lazy page fetching is not authorization filtering.','Keep this exact native revocation contract unavailable. Database-per-user or an application purge would change the contract and must be a separately labeled workload.',['src/adapters/turso.ts','src/contracts/access.ts','https://docs.turso.tech/sync/local-sync-server','https://docs.turso.tech/sync/partial'])
add('electric','online-propagation','not-applicable','Not applicable','This direct-to-server write path performs no local commit.','Keep this milestone absent for the direct-write profile; a SQLite outbox profile can measure it separately without claiming native Electric persistence.',['src/adapters/electric.ts','src/recovery/electric-driver.ts','https://electric.ax/docs/sync/guides/writes'],'local_commit_p50_ms')
add('electric-tanstack','online-propagation','implement-milestone','Not measured','The adapter deliberately disables localCommit even though the collection exposes the optimistic local update; that is not a durable queue receipt.','Measure a local-visible milestone consistently for all clients, or use the durable native executor/storage path for local commit. Never use isPersisted, which includes remote settlement, as local-only time.',['src/adapters/electric-tanstack-runner.ts','src/contracts/collaboration.ts','node_modules/@tanstack/db/src/transactions.ts'],'local_commit_p50_ms')
for stack,scenario,label,reason,action in [
 ('jazz-v2','bootstrap','Not reached','Cold 100k startup exceeded 90 seconds; warm startup was never reached.','Run warm and cold as independent cases. Diagnose count-query materialization, ingestion and retained server history before changing a uniform deadline.'),
 ('jazz-v2','conflict-update-delete','Did not converge','Writer and other clients disagree after acknowledged writes and a 90-second deadline.','Trace the target tombstone, reconnection and native subscriptions. Retain failure until all clients agree; do not force an assumed winner.'),
 ('jazz-v2','permission-change','Purge timed out','The 60,000 ms purge deadline expires: online queries hide revoked rows but local storage retains them; reconnect also leaves queries stale. Fresh-client authorization passes.','Separate query visibility from native purge, and investigate reconnect/subscription behavior. Keep the observed failure, not a skipped case.'),
 ('syncular-rust','blob-flow','Setup timed out','The 30,000 ms realtime-sync deadline expires before transfer. A harness session-readiness race is possible but unproven.','Trace session assignment, hello and the first sync frame; test a readiness/buffering fix separately, then rerun the whole attachment case.')]:
 add(stack,scenario,'diagnose',label,reason,action,['results/diagnostics/final-publication/TIMEOUT-REVIEW.json','docs/investigations/tuned-publication-failures.md'])
for scenario,reason,action in [
 ('replica-reopen','One prior setup connection failed; two runs succeeded.','Keep the failure in the record; capture both endpoints before assigning a cause.'),
 ('connected-fanout','One prior attempt ran out of disk during 25-reader setup; two runs succeeded.','Add a preflight disk budget and bounded artifact retention outside measurements.'),
 ('reconnect-storm','One prior attempt ran out of disk during 25-reader setup; two runs succeeded.','Add a preflight disk budget and bounded artifact retention outside measurements.')]:
 add('turso',scenario,'retain-success-with-failure-note','Measured',reason,action,['docs/investigations/tuned-publication-failures.md'])
# Publication selections remain immutable. Distinguish them from later code fixes.
verified={('electric','deep-relationship-query'),('jazz-v2','deep-relationship-query'),('electric','replica-reopen'),('zero','replica-reopen'),('electric-tanstack','offline-restart'),('syncular-rust','blob-flow')}
for c in cases:
 if (c['stack'],c['scenario']) in verified:
  c['disposition']='verified-awaiting-publication'
  c['reason']=('The published attempts predate a working implementation. Full correctness checks now pass; these development timings have not replaced the published campaigns. See the missing-coverage investigation.' if c['stack']!='syncular-rust' else 'Published attempts timed out during reader setup, before any transfer. The full attachment check now passes after fixing dropped early WebSocket frames; replacement campaign numbers are pending.')
  c['nextStep']='Collect at most three publication rounds using the fixed implementation; retain old attempts separately and do not pool development timings.'
  c['evidence'].append('results/diagnostics/coverage-fixes/VERIFICATION.json')
  selected=next(x for x in coverage['cases'] if (x['stack'],x['scenario'])==(c['stack'],c['scenario']))
  if selected['source']=='coverage-fixes':
   assert len(selected['attempts'])==1 and selected['attempts'][0]['outcome']=='completed'
   c.update(disposition='published-single-run',label='Measured',reason='The repaired implementation passed its complete workload and output checks in one predeclared publication run (n=1). Run-to-run variability is unknown.',nextStep='Retain the single-run caveat; investigate costs separately before any further campaign.')
   c['evidence'].append('results/reports/coverage-fixes/RESULTS.json')

reviewed={(c['stack'],c['scenario']) for c in cases}
missing={(c['stack'],c['scenario']) for c in coverage['cases'] if not c['attempts'] or any(a['outcome']!='completed' for a in c['attempts'])}
assert missing <= reviewed, missing-reviewed
assert len(cases)==22
files=sorted({p for c in cases for p in c['evidence'] if not p.startswith('https://')})
evidence=[dict(path=p,sha256=hashlib.sha256(Path(p).read_bytes()).hexdigest()) for p in files]
r={'scope':'Every current skipped/failed case plus missing local-commit cells and earlier Turso failures: 22 client/case entries. Immutable trial statuses remain unchanged. Six repaired cases have explicit publication or development dispositions below.','coverageSha256':hashlib.sha256(Path('COVERAGE.json').read_bytes()).hexdigest(),'policy':'Missing adapters, inconvenient runtime choices and setup failures are work to do, not product limitations. Only a documented lack of an equivalent workload or an inapplicable milestone justifies omission.','cases':cases,'evidence':evidence,'optionalBrowserRuntime':'src/browser/adapter.ts implements only Electric and Zero collaboration; other Chromium combinations are implementation gaps and are not claimed as tested product limitations. The native Rust executable is not a browser SDK.'}
Path('results/diagnostics/final-publication/COVERAGE-REVIEW.json').write_text(json.dumps(r,indent=2)+'\n')
print('Reviewed',len(cases),'entries; every selected non-completed case covered.')
