import { benchmarkRoot } from './paths.ts';
import type { StackId, StackSpec } from './types';

export const stacks: StackSpec[] = [
  {
    id: 'syncular',
    title: 'Syncular',
    composeFile: `${benchmarkRoot}/stacks/syncular/docker-compose.yml`,
    composeProjectName: 'offline-sync-bench-syncular',
    buildFingerprintPaths: [
      `${benchmarkRoot}/stacks/syncular/Dockerfile`,
      `${benchmarkRoot}/stacks/syncular/docker-compose.yml`,
      `${benchmarkRoot}/stacks/syncular/syncular-app`,
    ],
    databaseUrl: 'postgresql://bench:bench@localhost:55432/bench?sslmode=disable',
    adminBaseUrl: 'http://localhost:3211',
    syncBaseUrl: 'http://localhost:3210/api',
    syncRealtimeBaseUrl: 'ws://localhost:3210/api/sync/realtime',
    services: {
      sync: 'syncular',
      admin: 'admin',
      postgres: 'postgres',
    },
    capabilities: {
      bootstrap: 'native',
      onlinePropagation: 'native',
      offlineReplay: 'native',
      reconnectStorm: 'native',
      largeOfflineQueue: 'native',
      localQuery: 'native',
      deepRelationshipQuery: 'native',
      permissionChange: 'native',
      blobFlow: 'native',
    },
    notes: [
      'Syncular v2 from the published npm packages (@syncular/*@0.16.1, exact-pinned): the real @syncular/client SyncClient (bun:sqlite local database) against the v2 server with relational Postgres server storage (real per-app tables).',
      'Admin writes are engine-mediated — there is no CDC because the server tables are engine-owned; the bench-admin equivalents commit through the storage API and wake clients via the engine Postgres LISTEN/NOTIFY fanout.',
      'Blobs are delivered through presigned MinIO upload grants and download URLs via the product blob transport.',
      'Subscriptions are per-project scope subscriptions, so membership revocation empties one subscription scope and triggers the native client-side purge.',
    ],
  },
  {
    id: 'syncular-rust',
    title: 'Syncular Rust Client',
    composeFile: `${benchmarkRoot}/stacks/syncular/docker-compose.yml`,
    composeProjectName: 'offline-sync-bench-syncular',
    buildFingerprintPaths: [
      `${benchmarkRoot}/stacks/syncular/Dockerfile`,
      `${benchmarkRoot}/stacks/syncular/docker-compose.yml`,
      `${benchmarkRoot}/stacks/syncular/syncular-app`,
    ],
    databaseUrl: 'postgresql://bench:bench@localhost:55432/bench?sslmode=disable',
    adminBaseUrl: 'http://localhost:3211',
    syncBaseUrl: 'http://localhost:3210/api',
    syncRealtimeBaseUrl: 'ws://localhost:3210/api/sync/realtime',
    services: {
      sync: 'syncular',
      admin: 'admin',
      postgres: 'postgres',
    },
    capabilities: {
      bootstrap: 'native',
      onlinePropagation: 'native',
      offlineReplay: 'native',
      reconnectStorm: 'native',
      largeOfflineQueue: 'native',
      localQuery: 'native',
      deepRelationshipQuery: 'native',
      permissionChange: 'native',
      blobFlow: 'native',
    },
    notes: [
      'Same Syncular v2 server stack (relational Postgres server storage, engine-mediated admin writes with Postgres LISTEN/NOTIFY fanout, presigned MinIO blobs) driven by the native Rust client.',
      'The Rust client (rusqlite core) runs as a harness-owned standalone bench binary built against the published crates (crates.io syncular-client/syncular-command/syncular-ffi 0.16.1, exact-pinned), speaking real HTTP+WebSocket to the Dockerized server — no browser, no WASM.',
      'Subscriptions are per-project scope subscriptions, matching the JS client workload shape.',
    ],
  },
  {
    id: 'electric',
    title: 'Electric',
    composeFile: `${benchmarkRoot}/stacks/electric/docker-compose.yml`,
    composeProjectName: 'offline-sync-bench-electric',
    buildFingerprintPaths: [
      `${benchmarkRoot}/services/bench-admin`,
      `${benchmarkRoot}/stacks/electric`,
    ],
    databaseUrl: 'postgresql://bench:bench@localhost:55433/bench?sslmode=disable',
    adminBaseUrl: 'http://localhost:3212',
    syncBaseUrl: 'http://localhost:3213',
    appBaseUrl: 'http://localhost:3224',
    services: {
      sync: 'electric',
      app: 'app',
      admin: 'admin',
      postgres: 'postgres',
    },
    capabilities: {
      bootstrap: 'native',
      onlinePropagation: 'native',
      offlineReplay: 'emulated',
      reconnectStorm: 'native',
      largeOfflineQueue: 'emulated',
      localQuery: 'native',
      deepRelationshipQuery: 'unsupported',
      permissionChange: 'native',
      blobFlow: 'unsupported',
    },
    notes: [
      'Uses Electric shape feeds directly for bootstrap and visibility timing.',
      'Permission-change convergence uses a benchmark-owned auth-scoped Electric shape proxy that derives project access from project_memberships.',
      'Offline replay uses a benchmark-owned Bun SQLite outbox to emulate durable client-side queuing.',
    ],
  },
  {
    id: 'electric-tanstack',
    title: 'Electric + TanStack DB',
    composeFile: `${benchmarkRoot}/stacks/electric/docker-compose.yml`,
    composeProjectName: 'offline-sync-bench-electric',
    buildFingerprintPaths: [
      `${benchmarkRoot}/services/bench-admin`,
      `${benchmarkRoot}/stacks/electric`,
    ],
    databaseUrl: 'postgresql://bench:bench@localhost:55433/bench?sslmode=disable',
    adminBaseUrl: 'http://localhost:3212',
    syncBaseUrl: 'http://localhost:3213',
    appBaseUrl: 'http://localhost:3224',
    services: {
      sync: 'electric',
      app: 'app',
      admin: 'admin',
      postgres: 'postgres',
    },
    capabilities: {
      bootstrap: 'native',
      onlinePropagation: 'native',
      offlineReplay: 'native',
      reconnectStorm: 'unsupported',
      largeOfflineQueue: 'native',
      localQuery: 'native',
      deepRelationshipQuery: 'native',
      permissionChange: 'native',
      blobFlow: 'unsupported',
    },
    notes: [
      'Uses the official Electric collection adapter with TanStack DB 0.6 SQLite persistence and the official TanStack offline-transactions outbox.',
      'Writes go through an idempotent benchmark backend and return the Postgres transaction ID from the same transaction so TanStack can await the matching Electric event.',
      'Local and relationship queries run through the TanStack DB query engine over Electric-materialized, SQLite-persisted collections.',
    ],
  },
  {
    id: 'zero',
    title: 'Zero',
    composeFile: `${benchmarkRoot}/stacks/zero/docker-compose.yml`,
    composeProjectName: 'offline-sync-bench-zero',
    buildFingerprintPaths: [
      `${benchmarkRoot}/services/zero-bench-app`,
      `${benchmarkRoot}/stacks/zero`,
      `${benchmarkRoot}/services/bench-admin`,
    ],
    databaseUrl: 'postgresql://bench:bench@localhost:55434/bench?sslmode=disable',
    adminBaseUrl: 'http://localhost:3216',
    syncBaseUrl: 'http://localhost:3214',
    appBaseUrl: 'http://localhost:3215',
    services: {
      sync: 'zero-cache',
      app: 'app',
      admin: 'admin',
      postgres: 'postgres',
    },
    capabilities: {
      bootstrap: 'native',
      onlinePropagation: 'native',
      offlineReplay: 'unsupported',
      reconnectStorm: 'unsupported',
      largeOfflineQueue: 'unsupported',
      localQuery: 'native',
      deepRelationshipQuery: 'native',
      permissionChange: 'unsupported',
      blobFlow: 'unsupported',
    },
    notes: [
      'Uses a real zero-cache service plus a minimal benchmark app implementing query and mutate endpoints.',
      'Offline replay is marked unsupported because Zero does not target durable offline write queues in this deployment model.',
      'Local-query coverage uses the native Zero local cache and query materialization path.',
    ],
  },
  {
    id: 'powersync',
    title: 'PowerSync',
    composeFile: `${benchmarkRoot}/stacks/powersync/docker-compose.yml`,
    composeProjectName: 'offline-sync-bench-powersync',
    buildFingerprintPaths: [
      `${benchmarkRoot}/services/powersync-bench-app`,
      `${benchmarkRoot}/stacks/powersync`,
      `${benchmarkRoot}/services/bench-admin`,
    ],
    databaseUrl: 'postgresql://bench:bench@localhost:55435/bench?sslmode=disable',
    adminBaseUrl: 'http://localhost:3219',
    syncBaseUrl: 'http://localhost:3217',
    appBaseUrl: 'http://localhost:3218',
    services: {
      sync: 'powersync',
      app: 'app',
      admin: 'admin',
      postgres: 'postgres',
      storage: 'storage-postgres',
    },
    capabilities: {
      bootstrap: 'native',
      onlinePropagation: 'native',
      offlineReplay: 'native',
      reconnectStorm: 'unsupported',
      largeOfflineQueue: 'native',
      localQuery: 'native',
      deepRelationshipQuery: 'native',
      permissionChange: 'unsupported',
      blobFlow: 'unsupported',
    },
    notes: [
      'Uses the official PowerSync service with Postgres-backed bucket storage and a benchmark-owned Bun backend.',
      'Client-side benchmarks run through the real Node SDK and its native upload queue.',
      'Local-query coverage runs against the native PowerSync local SQLite cache after first sync completes.',
      'Large offline queue replay extends the same native upload queue path to 100 / 500 / 1000 queued writes.',
    ],
  },
  {
    id: 'turso',
    title: 'Turso Sync',
    composeFile: `${benchmarkRoot}/stacks/turso/docker-compose.yml`,
    composeProjectName: 'offline-sync-bench-turso',
    buildFingerprintPaths: [
      `${benchmarkRoot}/services/turso-bench-admin`,
      `${benchmarkRoot}/stacks/turso`,
    ],
    adminBaseUrl: 'http://localhost:3226',
    syncBaseUrl: 'http://localhost:3225',
    services: {
      sync: 'turso',
      admin: 'admin',
    },
    capabilities: {
      bootstrap: 'native',
      onlinePropagation: 'native',
      offlineReplay: 'native',
      reconnectStorm: 'unsupported',
      largeOfflineQueue: 'native',
      localQuery: 'native',
      deepRelationshipQuery: 'native',
      permissionChange: 'unsupported',
      blobFlow: 'unsupported',
    },
    notes: [
      'Uses the official Turso Sync 0.7.2 client against the official tursodb 0.7.2 local sync server.',
      'Offline writes accumulate in Turso\'s native local database change log and replay through push(); the harness does not add an outbox.',
      'The benchmark uses whole-database sync, so row-level permission revocation and blob transport are unsupported rather than emulated.',
    ],
  },
  {
    id: 'jazz-v2',
    title: 'Jazz v2 (experimental)',
    composeFile: `${benchmarkRoot}/stacks/jazz-v2/docker-compose.yml`,
    composeProjectName: 'offline-sync-bench-jazz-v2',
    buildFingerprintPaths: [`${benchmarkRoot}/stacks/jazz-v2`],
    adminBaseUrl: 'http://localhost:3227',
    syncBaseUrl: 'http://localhost:3227',
    services: {
      sync: 'jazz',
      admin: 'jazz',
    },
    capabilities: {
      bootstrap: 'native',
      onlinePropagation: 'native',
      offlineReplay: 'native',
      reconnectStorm: 'unsupported',
      largeOfflineQueue: 'native',
      localQuery: 'emulated',
      deepRelationshipQuery: 'unsupported',
      permissionChange: 'unsupported',
      blobFlow: 'unsupported',
    },
    notes: [
      'Experimental lane using jazz-tools 2.0.0-alpha.53 and its official self-hosted server; results are excluded from stable headline rankings.',
      'Offline writes use the public JazzClient transport disconnect/reconnect API over a persistent local jazz-napi runtime; the harness does not add an outbox.',
      'Local list and search filters are native, while the aggregate portion is application-side because Jazz v2 alpha does not expose local aggregate queries.',
    ],
  },
];

export function getStack(stackId: StackId): StackSpec {
  const stack = stacks.find((candidate) => candidate.id === stackId);
  if (!stack) {
    throw new Error(`Unknown stack: ${stackId}`);
  }
  return stack;
}
