import { assertRustExecutable, executableIdentity } from './executables.ts';
import { writeFile, rename } from 'node:fs/promises';
import { createAdapter } from './adapters/index.ts';
import { executeBenchmark, isFailed } from './execution.ts';
import { getBenchmarkEnvironmentMetadata, getStackVersionMetadata } from './version-metadata.ts';
import type { StackId, ScenarioId } from './types.ts';
import { createBrowserAdapter } from './browser/adapter.ts';
import { validateClientRuntime, type ClientRuntime, type BrowserIdentity } from './browser/provenance.ts';
const [output, runId, stackId, scenarioId] = process.argv.slice(2);
if (!output || !runId || !stackId || !scenarioId) throw new Error('Trial requires output, campaign, stack and scenario');
const runtime = JSON.parse(process.env.BENCH_CAMPAIGN_RUNTIME || '{"kind":"native-host"}') as ClientRuntime;
validateClientRuntime(runtime);
const browserIdentity = process.env.BENCH_BROWSER_IDENTITY ? JSON.parse(process.env.BENCH_BROWSER_IDENTITY) as BrowserIdentity : undefined;
if (runtime.kind === 'chromium' && (!browserIdentity || !process.env.BENCH_BROWSER_BUNDLE)) throw new Error('Browser trial lacks campaign artifacts');
const binary = runtime.kind === 'native-host' && stackId === 'syncular-rust' && process.env.BENCH_EXPECTED_RUST_SHA256 ? process.env.SYNCULAR_RUST_BENCH_BIN : undefined;
if (binary) assertRustExecutable(binary, true);
const executable = binary ? executableIdentity(binary) : null;
const adapter = runtime.kind === 'chromium' ? createBrowserAdapter(stackId as StackId, runtime, browserIdentity!, process.env.BENCH_BROWSER_BUNDLE!) : createAdapter(stackId as StackId);
const result = await executeBenchmark({ runId, runDir: output }, adapter, scenarioId as ScenarioId);
if (binary) assertRustExecutable(binary, true);
result.metadata = { ...result.metadata, ...(runtime.kind === 'chromium' ? { clientRuntime: 'chromium' } : {}), ...(executable ? { executable: { ...executable } } : {}), ...getStackVersionMetadata(adapter.stack), benchmarkEnvironment: getBenchmarkEnvironmentMetadata() };
await writeFile(`${output}.tmp`, JSON.stringify(result, null, 2));
await rename(`${output}.tmp`, output);
process.exit(isFailed(result.status) ? 1 : 0);
